apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-dir-deployment
  labels:
    app: books-dir
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: books-dir
  template: 
    metadata: 
      labels:
        app: books-dir
    spec:
      containers:
      - name: books-dir
        image: vikasdfghjl/books_dir:latest
        ports:
        - containerPort: 5000